const state = {
  token: localStorage.getItem('library_token'),
  user: JSON.parse(localStorage.getItem('library_user') || 'null'),
  view: location.hash.slice(1) || 'books',
  books: []
};
const $ = (selector) => document.querySelector(selector);
const root = $('#root');
const roles = { READER: 'Độc giả', LIBRARIAN: 'Thủ thư', ADMIN: 'Quản trị viên' };
const labels = { PENDING: 'Chờ duyệt', BORROWING: 'Đang mượn', RETURNED: 'Đã trả', REJECTED: 'Đã từ chối/Hủy' };

function esc(value = '') { return String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char])); }
function can(...allowed) { return state.user && allowed.includes(state.user.role); }
function fmt(value) { return value ? new Date(value).toLocaleDateString('vi-VN') : '—'; }
function toast(message, type = 'success') {
  const element = $('#toast'); element.textContent = message;
  element.className = `fixed right-4 top-4 z-50 max-w-sm rounded-lg px-4 py-3 text-sm font-medium shadow-lg ${type === 'error' ? 'bg-red-600 text-white' : 'bg-emerald-600 text-white'}`;
  clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.add('hidden'), 3500);
}
async function api(path, method = 'GET', body) {
  const response = await fetch(`/api${path}`, { method, headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Yêu cầu thất bại');
  return data;
}
function setView(view) { state.view = view; location.hash = view; render(); }
function logout() { localStorage.removeItem('library_token'); localStorage.removeItem('library_user'); state.token = null; state.user = null; location.hash = ''; render(); }
function badge(status) { const colors = { PENDING:'bg-amber-100 text-amber-800', BORROWING:'bg-blue-100 text-blue-800', RETURNED:'bg-emerald-100 text-emerald-800', REJECTED:'bg-rose-100 text-rose-800' }; return `<span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${colors[status]}">${labels[status]}</span>`; }
function stockBadge(book) { const cls = book.available === 0 ? 'bg-rose-100 text-rose-700' : book.available <= 2 ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'; const text = book.available === 0 ? 'Hết sách' : book.available <= 2 ? 'Còn ít' : 'Còn nhiều'; return `<span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${cls}">${text}: ${book.available}/${book.quantity}</span>`; }
function loading() { return '<div class="rounded-xl border border-slate-200 bg-white p-8 text-center text-slate-500">Đang tải dữ liệu...</div>'; }
function layout(content) {
  const nav = [['books','Sách'], ['borrows','Mượn / Trả'], ...(can('ADMIN') ? [['users','Tài khoản']] : [])];
  root.innerHTML = `<header class="border-b border-slate-200 bg-white"><div class="mx-auto flex max-w-7xl flex-wrap items-center gap-4 px-4 py-3 sm:px-6"><button class="mr-auto flex items-center gap-2 text-left" data-nav="books"><span class="grid h-9 w-9 place-items-center rounded-lg bg-blue-700 font-bold text-white">L</span><span><b class="block">LibraFlow</b><small class="text-slate-500">Quản lý thư viện</small></span></button><nav class="order-3 flex w-full gap-1 overflow-x-auto sm:order-none sm:w-auto">${nav.map(([id, name]) => `<button data-nav="${id}" class="whitespace-nowrap rounded-md px-3 py-2 text-sm font-medium ${state.view === id ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100'}">${name}</button>`).join('')}</nav><div class="flex items-center gap-2"><span class="hidden text-right text-sm sm:block"><b class="block">${esc(state.user.fullName)}</b><small class="text-slate-500">${roles[state.user.role]}</small></span><button id="logout" class="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium hover:bg-slate-50">Đăng xuất</button></div></div></header><main class="mx-auto max-w-7xl p-4 sm:p-6">${content}</main>`;
  document.querySelectorAll('[data-nav]').forEach((button) => button.onclick = () => setView(button.dataset.nav)); $('#logout').onclick = logout;
}
function showModal(html, bind) { const modal = $('#modal'); modal.className = 'fixed inset-0 z-40 flex items-center justify-center bg-slate-950/50 p-4'; modal.innerHTML = `<div class="modal-card w-full max-w-lg rounded-xl bg-white p-6 shadow-2xl">${html}</div>`; modal.querySelectorAll('[data-close]').forEach((button) => button.onclick = closeModal); if (bind) bind(modal); }
function closeModal() { $('#modal').className = 'fixed inset-0 z-40 hidden items-center justify-center bg-slate-950/50 p-4'; $('#modal').innerHTML = ''; }
function loginView() {
  root.innerHTML = `<section class="grid min-h-screen place-items-center bg-gradient-to-br from-blue-700 via-blue-600 to-slate-900 p-4"><div class="grid w-full max-w-4xl overflow-hidden rounded-2xl bg-white shadow-2xl md:grid-cols-2"><div class="bg-slate-900 p-8 text-white"><span class="grid h-12 w-12 place-items-center rounded-xl bg-blue-500 text-xl font-bold">L</span><h1 class="mt-6 text-3xl font-bold">LibraFlow</h1><p class="mt-3 text-slate-300">Hệ thống quản lý thư viện theo kiến trúc Microservices.</p><div class="mt-8 space-y-3 text-sm"><p class="font-semibold text-blue-200">Tài khoản demo</p>${[['reader','Độc giả'],['librarian','Thủ thư'],['admin','Quản trị viên']].map(([u,r]) => `<button data-demo="${u}" class="block w-full rounded-lg border border-slate-700 bg-slate-800 p-3 text-left hover:bg-slate-700"><b>${r}</b><br><span class="text-slate-300">${u} / 123456</span></button>`).join('')}</div></div><div class="p-8"><h2 class="text-2xl font-bold">Đăng nhập</h2><p class="mt-1 text-sm text-slate-500">Dùng tài khoản được cấp để tiếp tục.</p><form id="login-form" class="mt-8 space-y-4"><label class="block text-sm font-medium">Tên đăng nhập<input name="username" required minlength="3" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100"></label><label class="block text-sm font-medium">Mật khẩu<input name="password" type="password" required minlength="6" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100"></label><button class="w-full rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white hover:bg-blue-800">Đăng nhập</button></form></div></div></section>`;
  $('#login-form').onsubmit = async (event) => { event.preventDefault(); const button = event.submitter; button.disabled = true; button.textContent = 'Đang đăng nhập...'; try { const data = await api('/auth/login', 'POST', Object.fromEntries(new FormData(event.target))); state.token = data.token; state.user = data.user; localStorage.setItem('library_token', data.token); localStorage.setItem('library_user', JSON.stringify(data.user)); state.view = 'books'; location.hash = 'books'; toast(data.message); render(); } catch (error) { toast(error.message, 'error'); } finally { button.disabled = false; button.textContent = 'Đăng nhập'; } };
  document.querySelectorAll('[data-demo]').forEach((button) => button.onclick = () => { $('#login-form [name=username]').value = button.dataset.demo; $('#login-form [name=password]').value = '123456'; });
}
async function booksView() {
  layout(loading());
  try {
    state.books = await api('/books'); const categories = [...new Set(state.books.map((book) => book.category))].sort();
    layout(`<section class="space-y-5"><div class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-bold">Danh mục sách</h1><p class="mt-1 text-sm text-slate-500">Tìm kiếm theo tên, tác giả hoặc thể loại.</p></div>${can('LIBRARIAN','ADMIN') ? '<button id="add-book" class="rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-800">+ Thêm sách</button>' : ''}</div><div class="rounded-xl border border-slate-200 bg-white p-4"><div class="grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input id="book-search" placeholder="Tìm tên sách, tác giả..." class="rounded-lg border border-slate-300 px-3 py-2.5"><select id="book-category" class="rounded-lg border border-slate-300 px-3 py-2.5"><option value="">Tất cả thể loại</option>${categories.map((item) => `<option>${esc(item)}</option>`).join('')}</select><label class="flex items-center gap-2 rounded-lg border border-slate-300 px-3 text-sm"><input id="available-only" type="checkbox"> Còn sách</label></div></div><div id="book-table"></div></section>`);
    const refresh = () => { const query = $('#book-search').value.toLowerCase(); const category = $('#book-category').value; const available = $('#available-only').checked; bookTable(state.books.filter((book) => (!query || `${book.title} ${book.author} ${book.category}`.toLowerCase().includes(query)) && (!category || book.category === category) && (!available || book.available > 0))); };
    ['book-search','book-category','available-only'].forEach((id) => $(`#${id}`).oninput = refresh); bookTable(state.books); if ($('#add-book')) $('#add-book').onclick = () => bookModal();
  } catch (error) { layout(`<div class="rounded-xl bg-red-50 p-5 text-red-700">${esc(error.message)}</div>`); }
}
function bookTable(books) { $('#book-table').innerHTML = `<div class="table-wrap rounded-xl border border-slate-200 bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-600"><tr><th class="px-4 py-3">Tên sách</th><th class="px-4 py-3">Tác giả</th><th class="px-4 py-3">Thể loại</th><th class="px-4 py-3">Tồn kho</th><th class="px-4 py-3 text-right">Thao tác</th></tr></thead><tbody>${books.length ? books.map((book) => `<tr class="border-t border-slate-100"><td class="px-4 py-3 font-semibold">${esc(book.title)}</td><td class="px-4 py-3">${esc(book.author)}</td><td class="px-4 py-3">${esc(book.category)}</td><td class="px-4 py-3">${stockBadge(book)}</td><td class="px-4 py-3 text-right">${can('READER') ? `<button data-borrow="${book.id}" ${book.available === 0 ? 'disabled' : ''} class="rounded-md bg-blue-700 px-3 py-1.5 font-medium text-white enabled:hover:bg-blue-800 disabled:cursor-not-allowed disabled:bg-slate-300">Mượn</button>` : can('LIBRARIAN','ADMIN') ? `<button data-edit-book="${book.id}" class="rounded-md border border-slate-300 px-3 py-1.5 font-medium hover:bg-slate-50">Sửa</button>` : '—'}</td></tr>`).join('') : '<tr><td colspan="5" class="px-4 py-10 text-center text-slate-500">Không tìm thấy sách phù hợp.</td></tr>'}</tbody></table></div>`; document.querySelectorAll('[data-borrow]').forEach((button) => button.onclick = () => borrowModal(state.books.find((book) => book.id === Number(button.dataset.borrow)))); document.querySelectorAll('[data-edit-book]').forEach((button) => button.onclick = () => bookModal(state.books.find((book) => book.id === Number(button.dataset.editBook)))); }
function bookModal(book) { const editing = Boolean(book); showModal(`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">${editing ? 'Cập nhật sách' : 'Thêm sách'}</h2><button data-close class="text-2xl text-slate-500">×</button></div><form id="book-form" class="mt-5 grid gap-4"><label class="text-sm font-medium">Tên sách<input required name="title" maxlength="200" value="${esc(book?.title)}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><label class="text-sm font-medium">Tác giả<input required name="author" maxlength="120" value="${esc(book?.author)}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><label class="text-sm font-medium">Thể loại<input required name="category" maxlength="80" value="${esc(book?.category)}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><label class="text-sm font-medium">Số lượng<input required name="quantity" type="number" min="1" value="${book?.quantity || ''}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><button class="rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white">${editing ? 'Lưu thay đổi' : 'Thêm sách'}</button></form>`, () => { $('#book-form').onsubmit = async (event) => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await api(`/books${editing ? `/${book.id}` : ''}`, editing ? 'PUT' : 'POST', Object.fromEntries(new FormData(event.target))); closeModal(); toast(editing ? 'Đã cập nhật sách' : 'Đã thêm sách'); booksView(); } catch (error) { toast(error.message, 'error'); button.disabled = false; } }; }); }
function borrowModal(book) { showModal(`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">Xác nhận yêu cầu mượn</h2><button data-close class="text-2xl text-slate-500">×</button></div><p class="mt-4 rounded-lg bg-blue-50 p-3 text-sm"><b>${esc(book.title)}</b><br>${esc(book.author)} · ${book.available}/${book.quantity} bản còn</p><p class="mt-3 text-sm text-slate-600">Yêu cầu sẽ chờ thủ thư duyệt. Tồn kho chỉ giảm sau khi duyệt.</p><form id="borrow-form" class="mt-4"><label class="text-sm font-medium">Ghi chú (không bắt buộc)<textarea name="note" maxlength="500" class="mt-1 w-full rounded-lg border border-slate-300 p-3"></textarea></label><button class="mt-4 w-full rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white">Gửi yêu cầu</button></form>`, () => { $('#borrow-form').onsubmit = async (event) => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await api('/borrows', 'POST', { bookId: book.id, ...Object.fromEntries(new FormData(event.target)) }); closeModal(); toast('Đã gửi yêu cầu mượn, chờ thủ thư duyệt.'); booksView(); } catch (error) { toast(error.message, 'error'); button.disabled = false; } }; }); }
async function borrowsView() {
  layout(loading());
  try {
    const endpoint = can('READER') ? '/borrows/my' : '/borrows'; const records = await api(endpoint);
    layout(`<section class="space-y-5"><div class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-bold">${can('READER') ? 'Phiếu mượn của tôi' : 'Quản lý mượn / trả'}</h1><p class="mt-1 text-sm text-slate-500">Hạn mượn mặc định 14 ngày từ ngày duyệt.</p></div>${can('LIBRARIAN','ADMIN') ? `<span class="rounded-full bg-amber-100 px-3 py-2 text-sm font-semibold text-amber-800">${records.filter((r) => r.status === 'PENDING').length} phiếu chờ duyệt</span>` : ''}</div><div class="flex flex-wrap gap-2" id="status-filters">${[['','Tất cả'],['PENDING','Chờ duyệt'],['BORROWING','Đang mượn'],['RETURNED','Đã trả'],['REJECTED','Từ chối/Hủy']].map(([value,label]) => `<button data-status="${value}" class="rounded-full border border-slate-300 px-3 py-1.5 text-sm hover:bg-slate-100">${label}</button>`).join('')}</div><div id="borrow-table"></div></section>`);
    const draw = (status = '') => { const rows = records.filter((record) => !status || record.status === status); $('#borrow-table').innerHTML = `<div class="table-wrap rounded-xl border border-slate-200 bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-600"><tr><th class="px-4 py-3">Mã</th>${can('READER') ? '' : '<th class="px-4 py-3">Độc giả</th>'}<th class="px-4 py-3">Sách</th><th class="px-4 py-3">Ngày yêu cầu</th><th class="px-4 py-3">Hạn trả</th><th class="px-4 py-3">Trạng thái</th><th class="px-4 py-3 text-right">Thao tác</th></tr></thead><tbody>${rows.length ? rows.map((r) => `<tr class="border-t border-slate-100"><td class="px-4 py-3">#${r.id}</td>${can('READER') ? '' : `<td class="px-4 py-3">${esc(r.userName)}</td>`}<td class="px-4 py-3 font-semibold">${esc(r.bookTitle)}${r.rejectReason ? `<small class="mt-1 block font-normal text-rose-700">${esc(r.rejectReason)}</small>` : ''}</td><td class="px-4 py-3">${fmt(r.requestDate)}</td><td class="px-4 py-3">${fmt(r.dueDate)}</td><td class="px-4 py-3">${badge(r.status)}</td><td class="px-4 py-3 text-right">${borrowActions(r)}</td></tr>`).join('') : `<tr><td colspan="${can('READER') ? 6 : 7}" class="px-4 py-10 text-center text-slate-500">Chưa có phiếu phù hợp.</td></tr>`}</tbody></table></div>`; bindBorrowActions(); };
    document.querySelectorAll('[data-status]').forEach((button) => button.onclick = () => draw(button.dataset.status)); draw();
  } catch (error) { layout(`<div class="rounded-xl bg-red-50 p-5 text-red-700">${esc(error.message)}</div>`); }
}
function borrowActions(record) { if (can('READER') && record.status === 'PENDING') return `<button data-action="cancel" data-id="${record.id}" class="rounded-md border border-rose-300 px-3 py-1.5 text-rose-700 hover:bg-rose-50">Hủy yêu cầu</button>`; if (can('LIBRARIAN','ADMIN') && record.status === 'PENDING') return `<button data-action="approve" data-id="${record.id}" class="rounded-md bg-blue-700 px-3 py-1.5 text-white">Duyệt</button> <button data-action="reject" data-id="${record.id}" class="rounded-md border border-rose-300 px-3 py-1.5 text-rose-700">Từ chối</button>`; if (can('LIBRARIAN','ADMIN') && record.status === 'BORROWING') return `<button data-action="return" data-id="${record.id}" class="rounded-md bg-emerald-700 px-3 py-1.5 text-white">Xác nhận trả</button>`; return '—'; }
function bindBorrowActions() { document.querySelectorAll('[data-action]').forEach((button) => button.onclick = () => confirmBorrowAction(button.dataset.id, button.dataset.action)); }
function confirmBorrowAction(id, action) { const config = { approve:['Duyệt phiếu mượn','Duyệt phiếu sẽ giảm tồn kho một bản.'], reject:['Từ chối yêu cầu','Nhập lý do để độc giả biết.'], cancel:['Hủy yêu cầu','Yêu cầu sẽ được chuyển sang trạng thái đã hủy.'], return:['Xác nhận trả sách','Tồn kho sẽ tăng lại một bản.'] }[action]; showModal(`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">${config[0]}</h2><button data-close class="text-2xl text-slate-500">×</button></div><p class="mt-4 text-slate-600">${config[1]}</p>${action === 'reject' ? '<textarea id="reject-reason" class="mt-4 w-full rounded-lg border border-slate-300 p-3" minlength="3" placeholder="Lý do từ chối" required></textarea>' : ''}<div class="mt-6 flex justify-end gap-3"><button data-close class="rounded-lg border border-slate-300 px-4 py-2">Quay lại</button><button id="confirm-action" class="rounded-lg ${action === 'return' ? 'bg-emerald-700' : action === 'cancel' || action === 'reject' ? 'bg-rose-600' : 'bg-blue-700'} px-4 py-2 font-semibold text-white">Xác nhận</button></div>`, () => { $('#confirm-action').onclick = async () => { const reason = $('#reject-reason')?.value.trim(); if (action === 'reject' && (!reason || reason.length < 3)) return toast('Nhập lý do từ chối tối thiểu 3 ký tự', 'error'); const button = $('#confirm-action'); button.disabled = true; try { await api(`/borrows/${id}/${action}`, 'POST', action === 'reject' ? { reason } : undefined); closeModal(); toast(action === 'approve' ? 'Đã duyệt phiếu.' : action === 'return' ? 'Đã xác nhận trả sách.' : action === 'reject' ? 'Đã từ chối yêu cầu.' : 'Đã hủy yêu cầu.'); borrowsView(); } catch (error) { toast(error.message, 'error'); button.disabled = false; } }; }); }
async function usersView() { if (!can('ADMIN')) return setView('books'); layout(loading()); try { const users = await api('/users'); layout(`<section class="space-y-5"><div class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-bold">Quản trị tài khoản</h1><p class="mt-1 text-sm text-slate-500">Tạo tài khoản và phân vai trò cho hệ thống.</p></div><button id="add-user" class="rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">+ Tạo tài khoản</button></div><div class="table-wrap rounded-xl border border-slate-200 bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-600"><tr><th class="px-4 py-3">ID</th><th class="px-4 py-3">Họ tên</th><th class="px-4 py-3">Username</th><th class="px-4 py-3">Vai trò</th><th class="px-4 py-3">Ngày tạo</th></tr></thead><tbody>${users.map((u) => `<tr class="border-t border-slate-100"><td class="px-4 py-3">${u.id}</td><td class="px-4 py-3 font-semibold">${esc(u.fullName)}</td><td class="px-4 py-3">${esc(u.username)}</td><td class="px-4 py-3">${esc(roles[u.role])}</td><td class="px-4 py-3">${fmt(u.createdAt)}</td></tr>`).join('')}</tbody></table></div></section>`); $('#add-user').onclick = userModal; } catch (error) { layout(`<div class="rounded-xl bg-red-50 p-5 text-red-700">${esc(error.message)}</div>`); } }
function userModal() { showModal(`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">Tạo tài khoản</h2><button data-close class="text-2xl text-slate-500">×</button></div><form id="user-form" class="mt-5 grid gap-4"><label class="text-sm font-medium">Họ và tên<input name="fullName" required minlength="2" maxlength="100" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><label class="text-sm font-medium">Tên đăng nhập<input name="username" required pattern="[A-Za-z0-9._-]{3,50}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><label class="text-sm font-medium">Mật khẩu<input name="password" type="password" required minlength="6" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label><label class="text-sm font-medium">Vai trò<select name="role" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="READER">Độc giả</option><option value="LIBRARIAN">Thủ thư</option><option value="ADMIN">Quản trị viên</option></select></label><button class="rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white">Tạo tài khoản</button></form>`, () => { $('#user-form').onsubmit = async (event) => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await api('/users', 'POST', Object.fromEntries(new FormData(event.target))); closeModal(); toast('Đã tạo tài khoản'); usersView(); } catch (error) { toast(error.message, 'error'); button.disabled = false; } }; }); }
async function render() { if (!state.token || !state.user) return loginView(); if (!['books','borrows','users'].includes(state.view)) state.view = 'books'; if (state.view === 'books') return booksView(); if (state.view === 'borrows') return borrowsView(); return usersView(); }
window.addEventListener('hashchange', () => { state.view = location.hash.slice(1) || 'books'; render(); }); render();
